name: Deploy Public Contents

permissions:
  contents: write

on:
  push:
    branches:
      - development-changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout or create public branch
        run: |
          set -x  # Enable debug mode
          git checkout public || git checkout -b public
          git pull origin public || echo "Public branch does not exist or pull failed"

      - name: Copy contents of public folder from development-changes
        run: |
          set -x
          git checkout development-changes -- public/*

      - name: Check for changes
        run: |
          set -x
          git status
          if git diff --quiet; then
            echo "No changes detected in public folder. Skipping commit."
            exit 0
          fi

      - name: Commit and push changes
        run: |
          set -x
          git add .
          git commit -m "Auto-update files from inside the public folder"
          git push origin public
