name: Deploy Public Contents

permissions:
  contents: write

on:
  push:
    branches:
      - development-changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout or create public branch
        run: |
          set -eux
          git checkout public || git checkout -b public

      - name: Rebase public branch with the remote
        run: git pull --rebase origin public

      - name: Copy contents of public folder to root
        run: |
          set -eux
          cp -R public/* .

      - name: Check for changes
        run: |
          set -eux
          git status
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
            exit 0
          fi

      - name: Commit and push changes
        run: |
          set -eux
          git add .
          git commit -m "Auto-update files from inside the public folder"
          git push origin public --force-with-lease
